version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - ./init/mongodb:/docker-entrypoint-initdb.d
      - ./data/mongodb:/import_data
    ports:
      - "27017:27017"
    networks:
      - sympera_network
    restart: always
  
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d   # תיקיית אתחול
      - ./data/postgres:/import_data 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Rayaru1234
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    networks:
      - sympera_network
    restart: always

  sympera:
    build:
      context: .
      dockerfile: Dockerfile
    image: symper_services  
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./certs:/app/certs
      - ./.env:/app/.env
      - /app/frontend/node_modules
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - APP_ENV=development
      - PYTHONPATH=/app/backend
      - PYTHONUNBUFFERED=1
      - NODE_ENV=development
    networks:
      - sympera_network
    restart: unless-stopped
    #command: sh -c "/app/start.sh"

networks:
  sympera_network:
    driver: bridge

volumes:
  data:
  mongodb_data:
  postgres_data:
  backend:
  frontend:
  certs_data:
